ExamenFinalMvc/ExamenFinalMvc.Web/Controllers/EmpresasController.cs

using ExamenFinalMvc.Web.Funcionalidades.EditarEmpresas;
using ExamenFinalMvc.Web.Funcionalidades.EliminarEmpresas;
using ExamenFinalMvc.Web.Funcionalidades.ListarEmpresas;
using ExamenFinalMvc.Web.Funcionalidades.RegistrarEmpresas;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

 
namespace ExamenFinalMvc.Web.Controllers
{
    [Authorize]
    public class EmpresasController : Controller
    {
        // GET: Empresas
        public ActionResult Listar()
        {
            //var user = User.Identity.GetUserName();

            using (var listarEmpresa = new ListarEmpresaHandler())
            {
                return View(listarEmpresa.Ejecutar());
            }
        }

        [HttpGet]
        public ActionResult Registrar()
        {
            return View(new RegistrarEmpresaViewModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Registrar(RegistrarEmpresaViewModel modelo)
        {
            if (!ModelState.IsValid) return View(modelo);

            using (var registrarEmpresa = new RegistrarEmpresaHandler())
            {
                try
                {
                           registrarEmpresa.Ejecutar(modelo);
                    return RedirectToAction("Listar");

                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", ex.Message);
                    return View(modelo);
                }

            }
        }

       

        [HttpGet]
        public ActionResult Editar(int id)
        {

            using (var buscarEmpresa = new EditarEmpresaHandler())
            {
                return View(buscarEmpresa.BuscarId(id));
            }

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Editar(EditarEmpresaViewModel modelo)
        {
            if (!ModelState.IsValid) return View(modelo);

            using (var editarEmpresa = new EditarEmpresaHandler())
            {
                try
                {
                    editarEmpresa.Ejecutar(modelo);
                    return RedirectToAction("Listar");

                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", ex.Message);
                    return View(modelo);
                }

            }
        }


        [HttpGet]
        public ActionResult Eliminar(int id)
        {

            using (var buscarEmpresa = new EliminarEmpresaHandler())
            {
                return View(buscarEmpresa.BuscarId(id));
            }

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Eliminar(EliminarEmpresaViewModel modelo)
        {
            if (!ModelState.IsValid) return View(modelo);

            using (var editarEmpresa = new EliminarEmpresaHandler())
            {
                try
                {
                    editarEmpresa.Ejecutar(modelo);
                    return RedirectToAction("Listar");

                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", ex.Message);
                    return View(modelo);
                }

            }
        }


    }
}

ExamenFinalMvc/ExamenFinalMvc.Web/Controllers/FacturasController.cs
using ExamenFinalMvc.Web.Funcionalidades.EditarFacturas;
using ExamenFinalMvc.Web.Funcionalidades.EliminarFacturas;
using ExamenFinalMvc.Web.Funcionalidades.ListarFacturas;
using ExamenFinalMvc.Web.Funcionalidades.RegistrarFacturas;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ExamenFinalMvc.Modelo;
using System.IO;

namespace ExamenFinalMvc.Web.Controllers
{
    [Authorize]
    public class FacturasController : Controller
    {
        // GET: Facturas
        public ActionResult Listar(string ruc)
        {
            using (var listarEmpresa = new ListarFacturasHandler())
            {
                return View(listarEmpresa.Ejecutar(ruc));
            }
        }

        [HttpGet]
        public ActionResult Registrar(string ruc)
        {
            return View(new RegistrarFacturaViewModel() { Ruc = ruc });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Registrar(RegistrarFacturaViewModel modelo)
        {
            if (!ModelState.IsValid) return View(modelo);

            using (var registrarEmpresa = new RegistrarFacturaHandler())
            {
                try
                {

        
                    registrarEmpresa.Ejecutar(modelo);
                    return RedirectToAction("Listar", "Empresas");

                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", ex.Message);
                    return View(modelo);
                }

            }
        }


        [HttpGet]
        public ActionResult Editar(int id)
        {

            using (var buscarFactura = new EditarFacturaHandler())
            {
                return View(buscarFactura.BuscarId(id));
            }

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Editar(EditarFacturaViewModel modelo)
        {
            if (!ModelState.IsValid) return View(modelo);

            using (var editarFactura = new EditarFacturaHandler())
            {
                try
                {
                    editarFactura.Ejecutar(modelo);
                    return RedirectToAction("Listar");

                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", ex.Message);
                    return View(modelo);
                }

            }
        }


        [HttpGet]
        public ActionResult Eliminar(int id)
        {

            using (var buscarFactura = new EliminarFacturaHandler())
            {
                return View(buscarFactura.BuscarId(id));
            }

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Eliminar(EliminarFacturaViewModel modelo)
        {
            if (!ModelState.IsValid) return View(modelo);

            using (var eliminarFactura = new EliminarFacturaHandler())
            {
                try
                {
                    eliminarFactura.Ejecutar(modelo);
                    return RedirectToAction("Listar");

                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", ex.Message);
                    return View(modelo);
                }

            }
        }


      


    }
}

ExamenFinalMvc/ExamenFinalMvc.Web/Views/Empresas/Editar.cshtml
@model ExamenFinalMvc.Web.Funcionalidades.EditarEmpresas.EditarEmpresaViewModel

@{
    ViewBag.Title = "Editar";
}

<h2>Editar</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>EditarEmpresaViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.RUC, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RUC, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RUC, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RazonSocial, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RazonSocial, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RazonSocial, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Direccion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Direccion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Direccion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Departamento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Departamento, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Departamento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Provincia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Provincia, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Provincia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Distrito, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Distrito, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Distrito, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Rubro, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Rubro, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Rubro, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ExamenFinalMvc/ExamenFinalMvc.Web/Views/Empresas/Eliminar.cshtml
@model ExamenFinalMvc.Web.Funcionalidades.EliminarEmpresas.EliminarEmpresaViewModel

@{
    ViewBag.Title = "Eliminar";
}

<h2>Eliminar</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>EliminarEmpresaViewModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.RUC)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RUC)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RazonSocial)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RazonSocial)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Direccion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Direccion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Departamento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Departamento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Provincia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Provincia)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Distrito)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Distrito)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Rubro)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Rubro)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserId)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Listar")
        </div>
    }
</div>

ExamenFinalMvc/ExamenFinalMvc.Web/Views/Empresas/Listar.cshtml
@model IEnumerable<ExamenFinalMvc.Web.Funcionalidades.ListarEmpresas.ListarEmpresaViewModel>

@{
    ViewBag.Title = "Listar";
}

<h2>Listar</h2>

<p>
    @Html.ActionLink("Crear Empresa", "Registrar")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.RUC)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RazonSocial)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Direccion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Departamento)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Provincia)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Distrito)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Rubro)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UserId)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.RUC)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.RazonSocial)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Direccion)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Departamento)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Provincia)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Distrito)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Rubro)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UserId)
        </td>
        <td>
            <div class="btn-group">
                <button class="btn dropdown-toggle btn-xs"
                        data-toggle="dropdown">
                    <span>
                        <i class="glyphicon glyphicon-cog"></i>
                        <span class="caret"></span>
                    </span>
                </button>

                <ul class="dropdown-menu">
                    <li>
                        @Html.ActionLink(" ", "Editar", new { id = item.Id }, new { @class = "glyphicon glyphicon-eye-open" })
                    </li>
                    <li>
                        @Html.ActionLink(" ", "Eliminar", new { id = item.Id }, new { @class = "glyphicon glyphicon-trash" })
                    </li>
                    <li>
                        @Html.ActionLink("Agregar Factura", "Registrar", "Facturas", new { ruc = item.RUC }, new { @class = "glyphicon glyphicon-trash" })
                    </li>
                    <li>
                        @Html.ActionLink("Ver Facturas", "Listar", "Facturas", new { ruc = item.RUC }, new { @class = "glyphicon glyphicon-trash" })
                    </li>

                </ul>


            </div>

        </td>
    </tr>
}

</table>

ExamenFinalMvc/ExamenFinalMvc.Web/Views/Empresas/Registrar.cshtml
@model ExamenFinalMvc.Web.Funcionalidades.RegistrarEmpresas.RegistrarEmpresaViewModel

@{
    ViewBag.Title = "Registrar";
}

<h2>Registrar</h2>

@using Microsoft.AspNet.Identity
@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>RegistrarEmpresaViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.RUC, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RUC, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RUC, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RazonSocial, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RazonSocial, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RazonSocial, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Direccion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Direccion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Direccion, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.Departamento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Departamento, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Departamento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Provincia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Provincia, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Provincia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Distrito, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Distrito, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Distrito, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.Rubro, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Rubro, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Rubro, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
            </div>
        </div>

        <!-- Seccion de listas en cascadas-->

        <div id="empresa-ubigeo">
            <div class="form-group">
                @Html.LabelFor(model => model.Departamento, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-5">
                    @Html.HiddenFor(model => model.Departamento, new { @id = "departamento_nombre", @class = "departamento" })
                    @Html.DropDownList("departamento", Model.Departamentos,
                        new { @id = "persona_departamento", @class = "form-control departamento" })
                </div>
            </div>


            <div class="form-group">
                @Html.LabelFor(model => model.Provincia, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-5">
                    @Html.HiddenFor(model => model.Provincia, new { @id = "provincia_nombre", @class = "provincia" })
                    @Html.DropDownList("provincia", Model.Provincias,
                        new { @id = "persona_provincia", @class = "form-control provincia" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Distrito, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-5">
                    @Html.HiddenFor(model => model.Distrito, new { @id = "distrito_nombre", @class = "distrito" })
                    @Html.DropDownList("distrito", Model.Distritos,
                        new { @id = "persona_distrito", @class = "form-control distrito" })
                </div>
            </div>

        </div>




        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Listar")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/registraempresa")

}